name: Lint, test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
        # Run the steps below with the following versions of Node.js
        node-version: [8.x, 10.x, 12.x]

    steps:
    # Fetch the latest commit
    - name: Checkout
    uses: actions/checkout@v2

    # Setup Node.js using the appropriate version
    - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v1
    with:
        node-version: ${{ matrix.node-version }}

    # Install package dependencies
    - name: Install
    run: npm ci

    - name: Lint, test
    run: |
      npm i
      npm run lint && npm run test
