name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      
      - name: Lint
        run: |
          npm i
          npm run lint

      - name: Test
        run: |
          npm i
          npm run test